USE [TLW_FMS]
GO

/****** Object:  Table [dbo].[PAL_ENTRIES]    Script Date: 04/21/2012 23:29:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

ALTER TABLE [dbo].[PAL_ENTRIES]
ADD   PAL_ENTRY_ACTIVITY int NULL,
      PAL_TYPE_TEXT nchar(100) NULL,
      PAL_ACTIVITY_TEXT nchar(100) NULL
	
	

GO
